medical_diagnosis_task:
  description: >
    Analyze each candidate medical diagnosis in <diagnosis_text>{diagnosis_text}</diagnosis_text>, identify potential diagnoses, 
    and generate 2 (two) prioritized ICD-10 code suggestions for each potential diagnosis. 
    Provide a detailed explanation for each suggestion and include its relevance to the diagnosis. 
    Ensure each suggestion includes the code and the ICD-10 description.
  expected_output: >
    JSON formatted response containing:
    - A list of potential diagnoses derived from <diagnosis_text>{diagnosis_text}</diagnosis_text>.
    - For each diagnosis, up to 3 validated ICD-10 codes in prioritized order (based on medical relevance) and their descriptions.
    - Detailed explanations for why each code was chosen (rationale).
  agent: medical_coder
  output_file: medical_diagnosis_output.json

validation_task:
  description: >
    Validate the ICD-10 codes and descriptions (separately) generated in the medical diagnosis task using the icd10_database_tool. 
    For each suggested code:
    - Check if the code is valid in the ICD-10 database.
    - If the code is valid, confirm that its associated description matches the description suggested in the medical diagnosis task.
      Mark the code as invalid if the descriptions do not align, and provide an explanation.
    For each suggested description:
    - Search the ICD-10 database for a matching description.
    - If a match is found, note the associated code and mark it as valid and continue. 
    - If no match is found, mark the description as invalid, and provide an explanation.
    Highlight any discrepancies, mark each code and description as valid or invalid, and provide a detailed explanation for the validation status.
  expected_output: >
    JSON formatted response containing:
    - Validation results for each ICD-10 code and description suggested in the medical diagnosis task.
    - For each code:
        - Validation status (valid/invalid).
        - An explanation justifying the status.
        - Relevant URL linking to the validated ICD-10 WHO database entry.
    - For each description:
        - Validation status (valid/invalid).
        - An explanation justifying the status.
        - Relevant URL linking to the validated ICD-10 WHO database entry (if applicable).
    - Discrepancies between suggested and database descriptions must be highlighted and explained.
  agent: validation_agent
  output_file: validation_results.json

reporting_task:
  description: >
    Compile the results from the medical diagnosis and validation tasks into a structured JSON report. 
    Include all diagnoses, their suggested ICD-10 codes, validation statuses, database URLs, and the rationale for matching diagnoses with codes. 
    Highlight any discrepancies in the validation process.
  expected_output: >
    JSON formatted response containing:
    - Diagnoses, ICD-10 codes, validation statuses, and database URLs.
    - Detailed explanations for validation results.
    - The rationale for associating each diagnosis with its respective ICD-10 code.
    - Invalid diagnoses or descriptions should be reported with their URL as well, setting the value "url": null.
    - NO TEXT IS ALLOWED OUTSIDE THE JSON FORMATTED RESPONSE.
    - ENSURE RESULTS ARE JSON PARSABLE.
    - Example JSON with mock data with multiple diagnoses in diagnosis_text. Your output must have the same json ("dictionary") structure.
    {{
      "final_report": {{
        "diagnoses_report": [
          {{
            "diagnosis": "Asthma",
            "codes": [
              {{
                "code": "J45.909",
                "status": "invalid",
                "explanation": "Code J45.909 is not found in the ICD-10 database.",
                "rationale": "Unspecified asthma was selected as it covers generalized asthma without complications, aligning with the input."
              }},
              {{
                "code": "J45.901",
                "status": "invalid",
                "explanation": "Code J45.901 is not found in the ICD-10 database.",
                "rationale": "This code was chosen to represent asthma with acute exacerbation, which matches worsening symptoms described in potential diagnoses."
              }}
            ]
          }},
          {{
            "diagnosis": "Seasonal Allergies",
            "codes": [
              {{
                "code": "J30.2",
                "status": "valid",
                "explanation": "Code J30.2 is valid for Other seasonal allergic rhinitis.",
                "rationale": "This code was selected because seasonal allergic rhinitis aligns with allergy triggers varying across seasons.",
                "url": "https://icd.who.int/browse10/2019/en#/J30-J39"
              }},
              {{
                "code": "J30.1",
                "status": "valid",
                "explanation": "Code J30.1 is valid for Allergic rhinitis due to pollen.",
                "rationale": "This code was chosen specifically for pollen as a common seasonal allergen.",
                "url": "https://icd.who.int/browse10/2019/en#/J30-J39"
              }}
            ]
          }},
          {{
            "diagnosis": "Eczema",
            "codes": [
              {{
                "code": "L20.9",
                "status": "valid",
                "explanation": "Code L20.9 is valid for Atopic dermatitis, unspecified.",
                "rationale": "Atopic dermatitis is a type of eczema commonly reported without additional classifications, making this code appropriate.",
                "url": "https://icd.who.int/browse10/2019/en#/L20-L30"
              }},
              {{
                "code": "L30.9",
                "status": "valid",
                "explanation": "Code L30.9 is valid for Dermatitis, unspecified.",
                "rationale": "Dermatitis, unspecified, applies when no further details about the type of eczema are available.",
                "url": "https://icd.who.int/browse10/2019/en#/L20-L30"
              }}
            ]
          }}
        ],
        "validation_report": [
          {{
            "code": "D64.9",
            "description": "Anaemia, unspecified",
            "validation_status": "valid",
            "explanation": "The code D64.9 matches the description 'Anaemia, unspecified' in the ICD-10 WHO database.",
            "url": "https://icd.who.int/browse10/2019/en#/D60-D64"
          }},
          {{
            "code": "E11.9",
            "description": "Invalid code - Not found in the database",
            "validation_status": "invalid",
            "explanation": "The code E11.9 could not be found in the ICD-10 WHO database with the description provided. This suggests incorrect information, possibly a typo or an outdated code.",
            "url": null
          }},
          {{
            "code": "I10",
            "description": "Essential (primary) hypertension",
            "validation_status": "valid",
            "explanation": "The code I10 matches the description 'Essential (primary) hypertension' in the ICD-10 WHO database.",
            "url": "https://icd.who.int/browse10/2019/en#/I10-I15"
          }}
        ]
      }}
    }}
  agent: reporting_agent
  output_file: final_report_with_rationale.json