medical_diagnosis_task:
  description: >
    Analyze a candidate medical diagnosis: <diagnosis_text>{diagnosis_text}</diagnosis_text> and generate ICD-10 code suggestions, in a prioritized order (most medical relevance).
    Provide a detailed explanation for the choices made and validate each suggested ICD-10 codes and diagnosis descriptions against a pre-loaded ICD-10 database. Validation is made through the use of the icd10 datasbase tool.
  expected_output: >
    JSON formatted response with up to 3 validated ICD-10 suggestions for each potential diagnosis identified in <diagnosis_text>{diagnosis_text}</diagnosis_text> and an explanation oh why they fit. Include the url to the icd10 who database from the tool in the JSON response.  
  agent: medical_coder