medical_diagnosis_task:
  description: >
    Analyze the medical diagnosis text <diagnosis_text>{diagnosis_text}</diagnosis_text> 
    and suggest ICD-10 codes. Fallback to similar codes when exact matches are unavailable.
  expected_output: >
    JSON response containing:
    - Suggested ICD-10 codes and their descriptions.
    - Similar codes (if any) and reasons for their inclusion.
  agent: medical_coder
  output_file: medical_diagnosis_output.json

validation_task:
  description: >
    Validate the suggested ICD-10 codes and descriptions for the diagnosis text <diagnosis_text>{diagnosis_text}</diagnosis_text>. 
    Ensure each code's description aligns with the database. 
    Include fallback suggestions for similar codes when validation fails. And fallback codes for similar descriptions.
  expected_output: >
    JSON response containing:
    - Validation results for each suggested code.
    - Similar code suggestions if validation fails, with an explanation.
  agent: validation_agent
  output_file: validation_results.json

reporting_task:
  description: >
    Compile the results from the medical diagnosis and validation tasks for the diagnosis text <diagnosis_text>{diagnosis_text}</diagnosis_text> 
    into a structured JSON report. Include all diagnoses, their suggested ICD-10 codes, validation statuses, 
    database URLs, and the rationale for matching diagnoses with codes. Highlight any discrepancies in the validation process.
  expected_output: >
    JSON formatted response containing:
    - Diagnoses, ICD-10 codes, validation statuses, and database URLs.
    - Detailed explanations for validation results.
    - The rationale for associating each diagnosis with its respective ICD-10 code.
    - Invalid diagnoses or descriptions should be reported with their URL as well, setting the value "url": null.
    - NO TEXT IS ALLOWED OUTSIDE THE JSON FORMATTED RESPONSE.
    - ENSURE RESULTS ARE JSON PARSABLE.
    - Example JSON with mock data with multiple diagnoses in diagnosis_text. Your output must have the same json ("dictionary") structure.
    {{
      "final_report": {{
        "diagnoses_report": [
          {{
            "diagnosis": "Asthma",
            "codes": [
              {{
                "code": "J45.909",
                "status": "invalid",
                "explanation": "Code J45.909 is not found in the ICD-10 database.",
                "rationale": "Unspecified asthma was selected as it covers generalized asthma without complications, aligning with the input."
              }},
              {{
                "code": "J45.901",
                "status": "invalid",
                "explanation": "Code J45.901 is not found in the ICD-10 database.",
                "rationale": "This code was chosen to represent asthma with acute exacerbation, which matches worsening symptoms described in potential diagnoses."
              }}
            ]
          }},
          {{
            "diagnosis": "Seasonal Allergies",
            "codes": [
              {{
                "code": "J30.2",
                "status": "valid",
                "explanation": "Code J30.2 is valid for Other seasonal allergic rhinitis.",
                "rationale": "This code was selected because seasonal allergic rhinitis aligns with allergy triggers varying across seasons.",
                "url": "https://icd.who.int/browse10/2019/en#/J30-J39"
              }},
              {{
                "code": "J30.1",
                "status": "valid",
                "explanation": "Code J30.1 is valid for Allergic rhinitis due to pollen.",
                "rationale": "This code was chosen specifically for pollen as a common seasonal allergen.",
                "url": "https://icd.who.int/browse10/2019/en#/J30-J39"
              }}
            ]
          }},
          {{
            "diagnosis": "Eczema",
            "codes": [
              {{
                "code": "L20.9",
                "status": "valid",
                "explanation": "Code L20.9 is valid for Atopic dermatitis, unspecified.",
                "rationale": "Atopic dermatitis is a type of eczema commonly reported without additional classifications, making this code appropriate.",
                "url": "https://icd.who.int/browse10/2019/en#/L20-L30"
              }},
              {{
                "code": "L30.9",
                "status": "valid",
                "explanation": "Code L30.9 is valid for Dermatitis, unspecified.",
                "rationale": "Dermatitis, unspecified, applies when no further details about the type of eczema are available.",
                "url": "https://icd.who.int/browse10/2019/en#/L20-L30"
              }}
            ]
          }}
        ],
        "validation_report": [
          {{
            "code": "D64.9",
            "description": "Anaemia, unspecified",
            "validation_status": "valid",
            "explanation": "The code D64.9 matches the description 'Anaemia, unspecified' in the ICD-10 WHO database.",
            "url": "https://icd.who.int/browse10/2019/en#/D60-D64"
          }},
          {{
            "code": "E11.9",
            "description": "Invalid code - Not found in the database",
            "validation_status": "invalid",
            "explanation": "The code E11.9 could not be found in the ICD-10 WHO database with the description provided. This suggests incorrect information, possibly a typo or an outdated code.",
            "url": null
          }},
          {{
            "code": "I10",
            "description": "Essential (primary) hypertension",
            "validation_status": "valid",
            "explanation": "The code I10 matches the description 'Essential (primary) hypertension' in the ICD-10 WHO database.",
            "url": "https://icd.who.int/browse10/2019/en#/I10-I15"
          }}
        ]
      }}
    }}
  agent: reporting_agent
  output_file: final_report_with_rationale.json